# Generated by Django 3.2 on 2021-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='for_factory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='for_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='for_sundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='for_workers',
            field=models.BooleanField(default=False),
        ),
    ]
