# Generated by Django 3.2 on 2021-09-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('is_man', models.BooleanField(default=True)),
                ('is_woman', models.BooleanField(default=False)),
                ('is_married', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField()),
                ('cellphone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('college_evidence', models.CharField(blank=True, max_length=264, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=264, null=True)),
                ('college_score', models.IntegerField(blank=True, null=True)),
                ('name_of_college', models.CharField(blank=True, max_length=264, null=True)),
                ('english_mastery', models.CharField(blank=True, max_length=264, null=True)),
                ('computer_mastery', models.CharField(blank=True, max_length=264, null=True)),
                ('job_attendance', models.CharField(blank=True, max_length=264, null=True)),
                ('descriprion', models.TextField()),
                ('resome', models.FileField(upload_to='media/resome/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cooperation.jobopportunitymodel')),
            ],
        ),
    ]
