# Generated by Django 3.2 on 2021-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_applicationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='is_married',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='is_woman',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='is_single',
            field=models.BooleanField(default=True),
        ),
    ]
