# Generated by Django 3.2 on 2021-09-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0002_auto_20210922_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonusermodel',
            name='phone_number',
        ),
    ]
