# Generated by Django 3.2 on 2021-06-20 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 8, 58, 47, 739579, tzinfo=utc)),
        ),
    ]
