# Generated by Django 3.2 on 2021-09-29 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_contactusmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 13, 49, 34, 806471, tzinfo=utc)),
        ),
    ]
