# Generated by Django 3.2 on 2021-09-30 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20210929_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 9, 16, 26, 120804, tzinfo=utc)),
        ),
    ]
