# Generated by Django 3.2 on 2021-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('picture', models.ImageField(default='products/default/default.jpg', upload_to='products/')),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
    ]
