# Generated by Django 3.2 on 2021-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='is_package',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='is_radiator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='is_towerdryer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='is_waterheater',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
