# Generated by Django 3.2 on 2021-10-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210620_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='cataloge',
            field=models.FileField(default='sd', upload_to='cataloges/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
