# Generated by Django 3.2 on 2021-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211013_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='cataloge',
            field=models.FileField(default='products/default/default.jpg', upload_to='cataloges/'),
        ),
    ]
